version: "3.9"
services:
  postgres:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=wellnus
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:${DB_PORT}", "--", "/app/start.sh"]
    command: ["/app/main"]