CREATE TABLE IF NOT EXISTS wn_provider_setting (
    user_id BIGINT PRIMARY KEY REFERENCES wn_user(id) ON DELETE CASCADE,
    intro TEXT NOT NULL,
    topics TEXT[],
    unique(user_id),
    check(COALESCE(array_length(topics, 1), 0) > 0),
    check(topics <@ ARRAY[
        'Anxiety', 
        'OffMyChest', 
        'SelfHarm', 
        'Depression', 
        'SelfEsteem', 
        'Stress', 
        'Casual', 
        'Therapy', 
        'BadHabits', 
        'Rehabilitation',
        'Addiction',
        'Family',
        'Trauma',
        'Career',
        'Abandonment',
        'Relationships',
        'Identity',
        'LGBT'])
)